# Generated by Django 4.0.4 on 2022-10-21 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_variation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('Color', 'color'), ('Size', 'size')], max_length=100),
        ),
    ]
